### ISSUE TITLE
Google::Longrunning::OperationsClient prints warnings

### ISSUE THREAD

**Issue by blowmage** [googleapis/gax-ruby#102]
The generated GAPIC code that exposes operations endpoints prints the following warning, with no way to avoid it.

> \`service_path\` and \`port\` parameters are deprecated and will be removed

This is because the generated GAPIC code creates an Google::Longrunning::OperationsClient with the service_path argument, causing the warning.

**Comment by geigerj** [comment]
GAX 0.9.2, which removes this warning, has been released. Long term fix to follow the recommended LRO pattern is tracked as https://github.com/googleapis/toolkit/issues/1686.

**Comment by blowmage** [comment]
I'm seeing this warning when using google-gax 0.9.2, and only when an OperationsClient is being used. I'll investigate further.

**Comment by blowmage** [comment]
Oops, my mistake. I was running on an older branch that was missing the fixes in GoogleCloudPlatform/google-cloud-ruby#1824. Running on that code I am no longer seeing the warnings. I've even downloaded and inspected the gems from RubyGems to make sure the warning is gone. I believe this can be closed again. :)

**Comment by geigerj** [comment]
Good to hear!
