### ISSUE TITLE
Investigate removing some of proto coercion logic

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-ruby#110]
### What

Investigate if protobuf's coercion is safe (i.e., has the same behavior as GAX's). In cases where it is, consider simplifying GAX hash-to-proto coercion logic by removing duplicated functionality.

### Why

A GAX [utility](https://github.com/googleapis/gax-ruby/blob/master/lib/google/gax/util.rb) currently coerces hashes to protobuf messages. As of 3.5.0, the protobuf runtime handles at least some of these cases (see https://github.com/google/protobuf/pull/3627/).

cc: @landrito 

Updates https://github.com/google/protobuf/issues/3120.

**Comment by lukesneeringer** [comment]
Still under consideration; low priority.
(Replying here to bring the issue back into compliance.)

**Comment by jbolinger** [comment]
There are no plans for this so I'm going to close this until a need arises.
