### ISSUE TITLE
PathTemplate#match returning different params that given to PathTemplate#render

### ISSUE THREAD

**Issue by blowmage** [googleapis/gax-ruby#126]
While evaluating the behavior of `Google::Gax::PathTemplate`, I noticed a behavior that surprised me. Consider the following spec that I wrote to try to understand the existing behavior:

```ruby
it 'match returns the same params that render uses' do
  template = PathTemplate.new('v1/{name=parent/*}')
  params = { 'name' => 'parent/child' }
  path = 'v1/parent/child'

  expect(template.render(symbolize_keys(params))).to eq(path)

  expect(template.match(path)).to eq(params)
end
```

It fails with the following:

```
Failures:

  1) Google::Gax::PathTemplate match returns the same params that render uses
     Failure/Error: expect(template.match(path)).to eq(params)
     
       expected: {"name"=>"parent/child"}
            got: {"name"=>"child"}
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -"name" => "parent/child",
       +"name" => "child",
       
     # ./spec/google/gax/path_template_spec.rb:51:in `block (2 levels) in <top (required)>'
```

I find this surprising. Can someone verify that the behavior of `Google::Gax::PathTemplate#match` here is correct? If so, why isn't the value returned not matching the constraint given in the template?

**Comment by pongad** [comment]
I don't think I'm the expert here, but I think the behavior here is definitely incorrect. The name should be "parent/child".

**Comment by blowmage** [comment]
You will also note that I had to call `symbolize_keys` on the hash argument passed to `#render`, but the return value from `#match` was a hash with string keys. I don't understand why they are different. Shouldn't they either both use symbols keys or both use strings keys?

**Comment by eoogbe** [comment]
@jbolinger Any updates?

**Comment by jbolinger** [comment]
Path templates are being rewritten as part of https://github.com/googleapis/gapic-generator-ruby and this will be addressed in the next major release of this library.

**Comment by blowmage** [comment]
I'm going to close this. The plan is to remove template handling in this gem.
