### ISSUE TITLE
Merge kwargs and metadata in CallOptions

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gax-ruby#163]
`kwargs` was renamed to `metadata` since it was used exclusively for metadata, but the existing parameter was kept around to avoid a breaking change. `kwargs` should be dropped.

**Comment by blowmage** [comment]
Agreed. CallOptions is tied pretty closely to CallSettings, and #164 makes some changes to CallOptions so CallSettings can be removed. It also drops `kwargs` from CallOptions. If that PR is accepted I think it may satisfy this issue.
