### ISSUE TITLE
A dependency(grpc) of Google-gax is blocking our ruby upgrade (2.6.5 => 2.7.0)

### ISSUE THREAD

**Issue by omedale** [googleapis/gax-ruby#232]
#### Environment details
  - OS: macOs Catalina
  - Gem name and version:   google-cloud-text_to_speech (0.6.0)

#### Error
You get this error when you attempt to upgrade
```
bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
grpc-1.27.0-universal-darwin requires ruby version < 2.7.dev, >= 2.3,
which is incompatible with the current version, ruby 2.7.1p83
```

Please is there is plan on resolving this? 

You can find a related issue here https://github.com/grpc/grpc/issues/21514

**Comment by dazuma** [comment]
You should be able to `bundle update grpc` to get the latest version (1.32, which is compatible with Ruby 2.7.)

You should also consider updating google-cloud-text_to_speech. The latest version is 1.1.1. (The 0.x versions were built using an old code generator that we no longer support, and that may have some issues/warnings on Ruby 2.7. Note that newer versions do not even use google-gax anymore.)
