### ISSUE TITLE
Remove grpc dependency from api_callable.rb

### ISSUE THREAD

**Issue by jmuk** [googleapis/gax-ruby#26]
GAX files are usually designed to be orthogonal with underlying APIs, but catch_errors function assumes gRPC errors (and wrap it with GaxError).

This needs to be factored out. It shouldn't depend on grpc.
- list of known errors should be brought to call settings
- construct_settings should accept the list of known errors
- then, googleapis/toolkit should pass the gRPC errors

**Comment by jmuk** [comment]
cc: @tbetbetbe

**Comment by Landrito** [comment]
@jmuk This [toolkit PR](https://github.com/googleapis/toolkit/pull/273) and this [gax-ruby PR](https://github.com/googleapis/toolkit/pull/273) should be able to resolve this issue.
