### ISSUE TITLE
Document releases

### ISSUE THREAD

**Issue by blowmage** [googleapis/gax-ruby#61]
It would be very helpful to have release notes when a release is made, so we can track changes over time. I'd like to see the following:

1. Add a `CHANGELOG` file that lists releases and shows release notes.
2. Each release commit is tagged, so we can easily check out each release using git.
3. Create a GitHub Release using the tagged commit, and add the release notes to the release description.

**Comment by jbolinger** [comment]
@blowmage I have to do a new release for this soon. Feel free to add suggestions to #120 if you'd like so we can do this a little better going forward.

**Comment by jbolinger** [comment]
Cleaning up. Closing due to #120 Feel free to reopen if you have further suggestions.
