### ISSUE TITLE
Issue a 0.6.1 release

### ISSUE THREAD

**Issue by blowmage** [googleapis/gax-ruby#66]
We continue to see issues created because of the file permission problems in release 0.6.0 (#54). While this has been corrected in 0.7.0, some users continue to use the older versions and run into this issue. See GoogleCloudPlatform/google-cloud-ruby#1387

Unfortunately the release isn't tagged in the git repo, so it may be difficult to find the exact release commit in the repo. If you can't find the release commit, can you download the 0.6.0 gem, correct the gem's file permissions, update the version number to 0.6.1, package the gem, and then manually push the updated gem?

**Comment by jbolinger** [comment]
@blowmage is this something that's still needed? Trying to clear out old issues.

**Comment by blowmage** [comment]
We never saw a 0.6.1 release, but we have many releases since that have not had problems with file permission. I think this could be closed.
