### ISSUE TITLE
Stabilize rubocop style checking

### ISSUE THREAD

**Issue by jmuk** [googleapis/gax-ruby#68]
I've seen new rubocop failures happening on travis even if no changes are made on the related file. An example is https://github.com/googleapis/gax-ruby/pull/67/files (change of version string) and https://travis-ci.org/googleapis/gax-ruby/jobs/219042228.

This would be due to rubocop's behavioral changes; gax's gemspec (https://github.com/googleapis/gax-ruby/blob/master/google-gax.gemspec) says `s.add_development_dependency 'rubocop', '~> 0.32'`, and every new CI invocation installs the latest version of rubocop compatible with this spec, and sometimes the newer version of rubocop starts complaining new violations on existing code.

And note that `'~> 0.32'` means `>=0.32` and `<1.0`. The latest version of rubocop is `0.48.1`, which is compatible with this spec.

I think we should specify some exact version of rubocop (like `=0.48.0`) or at least allows only the patch level changes (like `~>0.48.0`), and then, manually bump the rubocop version dependency if we want additional style checking.

Thoughts?

**Comment by jbolinger** [comment]
Haven't seen any issues with this lately. Closing to clean up - will reopen if the unrelated failures occur.
