### ISSUE TITLE
gRPC error messages are missing metadata

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-ruby#70]
Originally reported by @frankyn

### What

Metadata is stripped from the gRPC error message.

### To reproduce

Call the Video Intelligence with a timeout <45s.

### Observed behavior

A vague/unhelpful error message is reported, specifying only that an argument is invalid, but not *which*:

```
api_callable.rb:349:in `rescue in block (2 levels) in retryable': GaxError Exception occurred in retry method that was not classified as transient, caused by 3:Request contains an invalid argument. (Google::Gax::RetryError)
```

### Expected behavior

The full error message, with details of what went wrong, should be displayed. The full error message is currently observable by setting the gRPC debug flags:

```
invalid_argument: RPC deadline too short. Mininum deadline per request: 45s. Requested deadline: 19s
```

**Comment by remi** [comment]
To clarify... IIUC the current working code looks like this:

```ruby
require "google/cloud/video_intelligence/v1beta1"

video_service_client = Google::Cloud::VideoIntelligence::V1beta1::VideoIntelligenceServiceClient.new
features             = [Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION]

options = Google::Gax::CallOptions.new retry_options: Google::Gax::RetryOptions.new(
  nil, Google::Gax::BackoffSettings.new(
		1000, 2.5, 120000, 120000, 1, 120000, 600000
  )
)

operation = video_service_client.annotate_video(path, features, options: options) do |operation|
  # ...
end
```

Can the acceptance criteria for this issue be for the working code to look like this, instead?  *(If not, I'd like to track this acceptance criteria somewhere)*

```ruby
require "google/cloud/video_intelligence/v1beta1"

video_service_client = Google::Cloud::VideoIntelligence::V1beta1::VideoIntelligenceServiceClient.new
features             = [Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION]

operation = video_service_client.annotate_video(path, features) do |operation|
  # ...
end
```

**Comment by geigerj** [comment]
@remi This will be fixed when I regenerate the GAPIC (hopefully can fit this in this afternoon). The current GAPIC has stale timeout configuration.

**Comment by lukesneeringer** [comment]
I believe this has been fixed for some time. @jbolinger to re-open if I am incorrect.
